### ISSUE TITLE
好像现在用不了了

### ISSUE THREAD

**Issue by NewRudy** [Y1ran/Free-VPN-for-Coursera#11]
好像现在用不了了

**Comment by Hathaway33** [comment]
SSR，用不了啊？

**Comment by keeplearning-again** [comment]
用不了+1

**Comment by Amberjay18** [comment]
免费的估计不行了 实在有需要的朋友 可以试试买个搬瓦工的最便宜的一键翻墙[Justmysocks](https://justmysocks1.net/members/aff.php?aff=7421&pid=2)的套餐试试
 5个节点自动换 （还有5.2%的优惠码：**JMS9272283**）

**Comment by Amberjay18** [comment]
哦哦 没事 我已经自己搞定了 谢谢😁
