### ISSUE TITLE
节点都用不了

### ISSUE THREAD

**Issue by VintageProgram** [Y1ran/Free-VPN-for-Coursera#7]
TCP连接测试都失败

**Comment by VintageProgram** [comment]
thanks

**Comment by sunnysun1975** [comment]
都用不了

**Comment by freeskyu** [comment]
可以试试免费的翻墙软件：[无界19.02正式版](https://github.com/sglfree/freesky/wiki/%E8%87%AA%E7%94%B1%E9%97%A8%E6%9C%80%E6%96%B0%E7%89%88%E4%B8%8B%E8%BD%BD-%E6%97%A0%E7%95%8C%E6%B5%8F%E8%A7%88%E6%9C%80%E6%96%B0%E6%AD%A3%E5%BC%8F%E7%89%88%E4%B8%8B%E8%BD%BD-%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6%E4%B8%8B%E8%BD%BD)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/27961182/56012584-b2fff900-5d1f-11e9-8220-4344718ea786.png)
